name: Test Ngrok Multi-Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Print OS Info
        run: |
          echo "Running on ${{ matrix.os }}"
          echo "This is just a test log."

      # ----- Linux -----
      - name: Download ngrok (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          curl -s -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok.zip

      # ----- Windows -----
      - name: Download ngrok (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          Invoke-WebRequest "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive "ngrok.zip" -DestinationPath .

      - name: Add Ngrok Token
        if: "!startsWith(matrix.os, 'macos')"
        run: ./ngrok authtoken 35siaobVPuzk5NX6rOFlRctcJes_4ct6tkribZJjSUNXPfpRM

      - name: Start Ngrok Tunnel
        if: "!startsWith(matrix.os, 'macos')" # macOS không cần
        run: |
          nohup ./ngrok tcp 8080 > ngrok.log 2>&1 & 
          echo "Launching Ngrok..."

      - name: Wait and Show ngrok logs
        if: "!startsWith(matrix.os, 'macos')"
        run: |
          sleep 5
          echo "===== NGROK LOGS ====="
          cat ngrok.log

      - name: Fake Logs
        run: |
          echo "Log test bắt đầu..."
          for i in {1..10}; do
            echo "Log số $i đang chạy..."
            sleep 1
          done